language: python
python: 3.5
dist: trusty
sudo: true

env:
  - TOXENV=py35 SOLC_VERSION=0.4.8

cache:
  - pip: true
  - directories:
#    - $TRAVIS_BUILD_DIR/solc-versions
    - $TRAVIS_BUILD_DIR/.tox --recreate

before_install:
  - if [ -n "$SOLC_VERSION" ]; then export SOLC_BINARY="$TRAVIS_BUILD_DIR/solc-versions/solc-$SOLC_VERSION/solc"; fi
  - if [ -n "$SOLC_VERSION" ]; then export LD_LIBRARY_PATH="$TRAVIS_BUILD_DIR/solc-versions/solc-$SOLC_VERSION"; fi
  - if [ -n "$SOLC_VERSION" ]; then sudo apt-get install -y tree unzip; fi
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update

install:
  - if [ ! -e "$SOLC_BINARY" ]; then /.$TRAVIS_BUILD_DIR/install_solc.sh; fi
  - travis_retry pip install setuptools --upgrade
  - pip install -U tox

before_script:
  - if [ -n "$SOLC_BINARY" ]; then $SOLC_BINARY --version; fi
  - export PATH=$PATH:`dirname $SOLC_BINARY`

# command to run tests, e.g. python setup.py test
script: tox -e ${TOXENV}


